### ISSUE TITLE
Places API Places Search: Nearby Places

### ISSUE THREAD

**Issue by kmiletti** [googlemaps/openapi-specification#265] opened 2022-02-03 01:53 UTC
`radius` is linked under "Optional Parameters" on [the docs page](https://developers.google.com/maps/documentation/places/web-service/search-nearby) but towards the bottom of the page in “Status codes returned by service” it's listed as being a possible reason for the `INVALID_QUERY` status code if it's missing due to being a required query parameter-- alongside `location` which IS listed as a necessary parameter
<img width="871" alt="Screen Shot 2022-02-02 at 8 41 09 PM" src="https://user-images.githubusercontent.com/11533745/152268222-a67d6307-dd00-45aa-83e5-5e1c3cb31c05.png">
<img width="890" alt="Screen Shot 2022-02-02 at 8 40 19 PM" src="https://user-images.githubusercontent.com/11533745/152268224-8eed9461-ed8f-407b-9ca1-9cb87b49af0b.png">
<img width="808" alt="Screen Shot 2022-02-02 at 8 41 26 PM" src="https://user-images.githubusercontent.com/11533745/152268277-04717e24-7fce-4d56-ab8f-d1e4b639d109.png">

**Comment by jpoehnelt** [comment] 2022-02-03 01:54
@kmiletti Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by jpoehnelt** [comment] 2022-02-03 02:00
duplicate of #264

**Closed by jpoehnelt** 2022-02-03 02:00 UTC
Labels: type: bug, triage me

**Comment by jpoehnelt** [comment] 2022-02-03 02:01
Thanks for reporting. I know this is confusing!

As stated in the linked issue, strictly speaking `radius` is optional when `pagetoken=` is provided.
